export const SET_ALERT = "SET_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN";
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";

export const GET_CURRENT_USER_BEGIN = "GET_CURRENT_USER_BEGIN";
export const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS";

export const GET_EMPLOYEE_TASK_BEGIN = "GET_EMPLOYEE_TASK_BEGIN";
export const GET_EMPLOYEE_TASK_SUCCESS = "GET_EMPLOYEE_TASK_SUCCESS";

export const GET_EMPLOYEE_SPECIFIC_TASK_BEGIN =
  "GET_EMPLOYEE_SPECIFIC_TASK_BEGIN";
export const GET_EMPLOYEE_SPECIFIC_TASK_SUCCESS =
  "GET_EMPLOYEE_SPECIFIC_TASK_SUCCESS";

export const GET_EMPLOYEE_BEGIN = "GET_EMPLOYEE_BEGIN";
export const GET_EMPLOYEE_SUCCESS = "GET_EMPLOYEE_SUCCESS";

export const REMOVE_EMPLOYEE_BEGIN = "REMOVE_EMPLOYEE_BEGIN";
export const REMOVE_EMPLOYEE_SUCCESS = "REMOVE_EMPLOYEE_SUCCESS";

export const EDIT_EMPLOYEE_BEGIN = "EDIT_EMPLOYEE_BEGIN";
export const EDIT_EMPLOYEE_SUCCESS = "EDIT_EMPLOYEE_SUCCESS";

export const CREATE_TASK_BEGIN = "CREATE_TASK_BEGIN";
export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS";

export const UPDATE_TASK_BEGIN = "UPDATE_TASK_BEGIN";
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";

export const CHANGE_PAGE = "CHANGE_PAGE";

export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_CURRENT_USER = "LOGOUT_CURRENT_USER";
