export { default as Home } from "./home/Home";
export { default as DashboardEmployee } from "./dashboardEmployee/DashboardEmployee";
export { default as Dashboard } from "./dashboard/Dashboard";
export { default as Register } from "./register/Register";
export { default as ProtectedRoute } from "./protectedRoute/ProtectedRoute";
export { default as Error } from "./error/Error";
export { default as AllEmployee } from "./dashboard/AllEmployee";
export { default as CreateTask } from "./dashboard/CreateTask";
export { default as Task } from "./dashboard/Task";
